// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CFStepSEMZ","status":true,"description":"(v.1.0) Adds step sound effects to Galv's Character Frames plugin","parameters":{"sFrames":"1,3","events":"true","-- Terrain Step SE --":"","Terrain 1":"Footstep3,50,100","Terrain 2":"Blow2,50,100","Terrain 3":"Footstep1,50,100","Terrain 4":"Footstep4,50,100","Terrain 5":"Footstep5,50,100","Terrain 6":"Hammer,50,100","Terrain 7":""}},
{"name":"GALV_CharacterFramesMZ","status":true,"description":"(v.1.0) Enables map character sheets to have more frames per character.","parameters":{"fSpeedMod":"f * 0.8","fileSymbol":"%"}}
];
