// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_MapTravelMZ","status":true,"description":"(v.1.1) A new scene allowing you to fast travel by selecting locations on a map","parameters":{"varMap":"1","xVar":"2","yVar":"3","textConfirm":"Travel","textCancel":"Cancel","windowWidth":"180","spriteFrames":"1","frameSpeed":"10"}}
];
