// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ThaiFontAutoAdjuster","status":true,"description":"ปรับตัวอักษรภาษาไทยไปตามยถากรรม","parameters":{}},
{"name":"GALV_MessageStylesMZ","status":true,"description":"(v.1.8) 'Show Text' windows float above characters and change visuals during game.","parameters":{"iIndicator":"2,0,-12","mPadding":"0,0,0,0","invertPos":"true","aGraphic":"WindowArrow","yOffset":"60"}}
];
