// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_MessageTimerMZ","status":true,"description":"(v.1.0) Visual timer for messages and choices.","parameters":{"globalTimer":"0","timerHeight":"10","timerMaxWidth":"","timerPadding":"10","timerPos":"top","timerOffset":"0,0","timerColor1":"0,0,0,0.5","timerColor2":"255,255,255,1"}}
];
