// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CC_ItemCrafting","status":true,"description":"Item Crafting System\r\n(Version 1.1.1)","parameters":{"menuCommandCrafting":"{\"show\":\"false\",\"enable\":\"true\",\"text\":\"Crafting\"}","menuCommandBreakdown":"{\"show\":\"false\",\"enable\":\"true\",\"text\":\"Breakdown\"}","textCustomize":"","textIngredients":"Ingredients:","textResults":"Results:","textTools":"Tools:","textPrice":"Price:","textNotes":"Notes:","logWindow":"","logWindowLines":"4","logWindowDisplayTime":"60","logWindowFadeTime":"30","logWindowForCrafting":"true","logWindowForBreakdown":"true"}},
{"name":"ThaiFontAutoAdjuster","status":true,"description":"ปรับตัวอักษรภาษาไทยไปตามยถากรรม","parameters":{}}
];
